import mysql.connector as c
con = c.connect(host = 'localhost', user = 'root', password = '914206', database = 'Onkar')
cursor=con.cursor()
Roll_no =int(input("Enter Student Rollno :"))
Name = input("Enter Student Name :")
Mark = int(input("Enter Student Marks :"))
query = " insert into Student values({}, '{}', {}) ".format(Roll_no, Name, Mark)
cursor.execute(query)
con.commit()
print("Data inserted successfully")